name: Deploy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    - name: NPM build APP for production
      run: npm run build

    - name: Delete Existing Files
      run: sudo sshpass -p "${{ secrets.SSH_PASS }}" -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf public_html/pantelismanikas/pantelismanikas.com/*'

    - name: Compress and Copy New Files to server
      run : |
            cd dist/
            tar -czvf ../../app.tar.gz ./
            cd ..
            cd ..
            sudo sshpass -p "${{ secrets.SSH_PASS }}" scp -v -o StrictHostKeyChecking=no -r app.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public_html/pantelismanikas/pantelismanikas.com

    - name: Uncompress new Files
      run : sudo sshpass -p "${{ secrets.SSH_PASS }}" -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd public_html/pantelismanikas/pantelismanikas.com && tar -xzvf app.tar.gz && rm app.tar.gz'
